### ISSUE TITLE
Error found with functions using Geom with PostgreSQL 12 and PostGIS 3

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#244] opened 2019-12-16 19:39 UTC
Using AB06 as an example, every polygons get error code -7779 (GeoIsValid) on field that use geometry (CASFRI_AREA, CASFRI_PERIMETER and PHOTO_YEAR). 

I broke down function into pieces. For example, TT_GeoIsValid returns valid geometry and TT_GeoArea returns the area of the polygons. But when I run TT_Translate, I get error code. 

When I run TT_Translate on PostgreSQL 11 with PostGIS 2.5, everything works fine.  It seems geometries is not handle the same way between version. and that may affect the engine.

**Comment by pedrogit** [comment] 2019-12-17 14:18
This is a major issue with PostGIS 3.0 which now implicitly convert geometries to jsonb strings:

"{"type":"MultiPolygon","coordinates":[[[[-1215622.21208424,1958542.76133615],[-1215520.4649829,1958511.37973457],[-1215556.89352013,1958392.9018458],[-1215559.9921751,1958396.49736617],[-1215562.82993668,1958401.40712003],[-1215565.95663456,1958409.23157887],[-1215568.68088484,1958414.5101095],[-1215616.01464679,1958515.05533708],[-1215622.21208424,1958542.76133615]]]]}"

when converting a whole row with the to_jsonb() PostgreSQL function instead of simply passing the canonical form e.g. :

"010600002032BF0D00010000000103000000010000001B00000021274B36868C32C11DEDE6C2".

Some ways to fix this:

1) Hack the PostGIS installation to make it behave, in this matter, like v.2.5. Ways to achieve this would be:

1.1) To comment out the ST_AsGeoJson() function, the jsonb() function and the CAST (geometry AS jsonb) definition in the postgis--3.0.0.sql file before installing PostGIS with CREATE EXTENSION. Tested. Works.

1.2 Install PostGIS with the postgis--3.0.0.sql file instead of installing it with CREATE EXTENSION  and then DROP the CAST and the jsonb() function. To be tested.

2) Refector the engine to move source rows around without converting them to jsonb. Lots of investigation work has already been done in this direction without much success up to now. Avenues cold be to pass them as RECORD or ARRAY. The problem is to be able to access values by their attribute names.

**Comment by edwardsmarc** [comment] 2019-12-17 16:39
So the problem is that the geometry format changes when a row is converted to json in the engine? And the engine and helper functions were set up to only use wkb geometries?

**Comment by MelinaHoule** [comment] 2019-12-18 20:15
I created a new database and ran the CREATE EXTENSION postgis with the temporary fixes and it works. The engine is now able to calculate the area, perimeter and extract photo_year from the photoyear table.

**Comment by edwardsmarc** [comment] 2020-10-29 15:49
Kristian plans on testing this but will wait until we have a more permanent fix.

**Comment by pedrogit** [comment] 2021-02-02 22:43
Fixed by engine https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/commit/6a161d8a00acb278177b624648a06f0ffb2464bd#diff-0c9913f96c28ac3e84cbac72f0bb0d1674aaa3f5560ea2f8d9b93c8bcad106a6

**Closed by pedrogit** 2021-02-02 22:43 UTC
Labels: blocker, bug, translation
